CC = gcc
CFLAGS = 
INCPATH =
LIBS = -lGLEW -lglfw3 -lGL -lX11 -lXi -lXrandr -lXxf86vm -lXinerama -lXcursor -lrt -lm -pthread -ldl

hello_window: main.c
	$(CC) $(CFLAGS) $(INCPATH) -o hello_window main.c $(LIBS)
